export const Bimbo = [
    { name: "Pan blanco 300g", price: 20.75, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Bimbo" },
    { name: "Pan blanco grande 620g", price: 40.67, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Bimbo" },
    { name: "Pan integral 300g", price: 23.24, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Bimbo" },
    { name: "Pan integral grande 620g", price: 43.16, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Bimbo" },
    { name: "Bimbollos 8p 450g", price: 43.16, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Bimbo" },
    { name: "Medias noches 8p 340g", price: 38.18, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Bimbo" },
    { name: "Tortillinas 15p 382.5 TR", price: 20.75, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Bimbo" },
    { name: "Tortillinas 22p 561g TR", price: 31.54, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Bimbo" },
    { name: "Tortillinas 30p 765g TR", price: 41.50, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Bimbo" },
    { name: "Pan molido clásico 210g", price: 23.24, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Bimbo" },
    { name: "Pan molido crujiente 175g", price: 23.24, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Bimbo" },
    { name: "Tostado clásico 210g", price: 28.22, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Bimbo" },
    { name: "Tostado integral 250g", price: 29.88, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Bimbo" },
    { name: "Tostado doble fibra 250g", price: 29.88, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Bimbo" },
    { name: "Mini tostado mantequilla 115g", price: 20.75, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Bimbo" },
    { name: "Tostada ondulada 30p 360g MR", price: 30.34, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Bimbo" },
    { name: "Totopos chilaquiles 280g", price: 26.24, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Bimbo" },
    { name: "Salmas 8p 144g", price: 25.11, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Bimbo" },
    { name: "Roles canela 6p 365g", price: 34.86, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Bimbo" },
    { name: "Roles canela 3p 180g", price: 20.75, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Bimbo" },
    { name: "Roles Glass 3p 205g", price: 20.75, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Bimbo" },
    { name: "Panqué mármol 280g", price: 34.86, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Bimbo" },
    { name: "Panqué pasas 280g", price: 34.86, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Bimbo" },
    { name: "Panqué nuez 280g", price: 34.86, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Bimbo" },
    { name: "Panqué chox 315g", price: 34.86, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Bimbo" },
    { name: "Mantecadas vainilla 188g", price: 26.56, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Bimbo" },
    { name: "Mantecadas nuez 184g", price: 26.56, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Bimbo" },
    { name: "Mantecadas chispas chocolate 190g", price: 26.56, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Bimbo" },
    { name: "Donas azucaradas 6p 158g", price: 18.26, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Bimbo" },
    { name: "Donaitas espolvoreadas 8p 140g", price: 18.26, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Bimbo" },
    { name: "Doners 120g", price: 20.75, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Bimbo" },
    { name: "Madalenas 3p 93g", price: 18.26, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Bimbo" },
    { name: "Panquesitos gotas chocolate 2p 140g", price: 18.26, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Bimbo" },
    { name: "Bimbuñuelos 6p 99g", price: 18.26, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Bimbo" },
    { name: "Bimbuñuelos Canela 6p 99g", price: 18.26, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Bimbo" },
    { name: "Conchas vainilla 2p 120g", price: 16.60, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Bimbo" },
    { name: "Rebanadas 55g", price: 6.64, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Bimbo" },
    { name: "Nito 1p 62g", price: 14.11, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Bimbo" },
    { name: "Nito duo 2p 124g", price: 20.75, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Bimbo" },
    { name: "Nito duo 2p 124g", price: 23.52, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Bimbo" },
    { name: "Little bites chispas 69g", price: 12.45, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Bimbo" },
    { name: "Little bites hershey's 69g", price: 12.45, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Bimbo" },
    { name: "Little bites Bob Sponja 5pz", price: 74.70, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Bimbo" },
    { name: "Colchones 6p 130g", price: 13.28, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Bimbo" },
    { name: "Crossantines choco 1p 32g", price: 5.74, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Bimbo" },
    { name: "Donitas espolvoreadas 52.5g", price: 8.30, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Bimbo" },
];