export const Marinela = [
    { name: "Barritas Fresa 75g", price: 15.12, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
    { name: "Barritas Piña 75g", price: 15.12, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
    { name: "Barritas Moras 75g", price: 15.12, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
    { name: "Bombonete 55g", price: 12.60, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
    { name: "Príncipe Chocolate 126g 12p", price: 20.16, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
    { name: "Príncipe Chocolate Blanco 126g", price: 20.16, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
    { name: "Príncipe Avellana 126g", price: 20.16, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
    { name: "Príncipe Doble Chocolate 126g", price: 20.16, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
    { name: "Príncipe Limón 126g", price: 20.16, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
    { name: "Príncipe Reese's 84g", price: 20.16, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
    { name: "Triki Trakes 85g", price: 18.47, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
    { name: "Triki Trakes Bombón 85g", price: 18.47, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
    { name: "Lords 98g", price: 16.80, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
    { name: "Plativolos 90g", price: 16.80, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
    { name: "Sponch 120g", price: 20.16, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
    { name: "Sponch Mango 124g", price: 20.16, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
    { name: "Suavicremas Chocolate 100g", price: 16.80, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
    { name: "Suavicremas Fresa 100g", price: 16.80, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
    { name: "Suavicremas Vainilla 100g", price: 16.80, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
    { name: "Polvorones 148g 6p + 2p", price: 20.16, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
    { name: "Canelitas 120g ", price: 20.16, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
    { name: "MaxiTubos Príncipe", price: 26.88, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
    { name: "MaxiTubos Triki Trakes", price: 26.88, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
    { name: "MaxiTubos Canelitas", price: 26.88, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
    { name: "MaxiTubos Polvorones", price: 26.88, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
    { name: "MaxiTubos Sponch", price: 26.88, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
    { name: "MaxiTubos Barritas Fresa", price: 26.88, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
    { name: "MaxiTubos Barritas Piña", price: 26.88, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
    { name: "Caja Bob Esponja", price: 25.20, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
    { name: "Pingüinos 3p 120g", price: 23.24, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
    { name: "Pingüinos 2p 80g", price: 18.26, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
    { name: "Pingüinos Hershey's 2p 80g", price: 18.26, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
    { name: "Pingüinos Calaverita 2p 80g", price: 18.26, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
    { name: "Choco Roles 100g", price: 18.26, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
    { name: "Rollo Fresa 75g", price: 14.94, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
    { name: "Gansito 50g", price: 14.94, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
    { name: "Gansito Duo", price: 9.95, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
    { name: "Gansito Premio", price: 16.60, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
    { name: "Dúo Napolitano 140g", price: 20.75, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
    { name: "Dúo Mini Pay Nuez 96g", price: 20.75, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
    { name: "Dúo Mini Pay Piña 110g", price: 20.75, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
    { name: "Dúo Mini Pay Fresa", price: 20.75, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
    { name: "Submarinos Chocolate 105g", price: 16.60, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
    { name: "Submarinos Fresa 105g", price: 16.60, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
    { name: "Submarinos Vainilla 105g", price: 16.60, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
    { name: "Rocko", price: 8.40, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
    { name: "Pastisetas Originales 90g", price: 23.52, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
    { name: "Pastisetas Sin Azúcar 90g", price: 25.20, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
    { name: "Deliciosas Vainilla 230g", price: 23.52, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
    { name: "Deliciosas Chocochispas 230g", price: 23.52, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
    { name: "Deliciosas Chochitos 230g", price: 23.52, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
    { name: "Deliciosas Bombón 170g", price: 25.20, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
    { name: "Deliciosas Animalitos 200g", price: 18.48, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Marinela" },
];