export const Sabritas = [
    { name: "Sabritas Original", price: 17.12, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    { name: "Sabritas Limón", price: 17.12, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    { name: "Sabritas Adobadas", price: 17.12, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    { name: "Sabritas Habanero", price: 17.12, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    { name: "Sabritas Especias", price: 17.12, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    { name: "Sabritas Flamint Hot", price: 17.12, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    { name: "Sabritas Receta Crujiente", price: 17.12, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    { name: "Ruffles Original", price: 17.12, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    { name: "Ruffles Queso", price: 17.12, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    { name: "Ruffles Jalapeño", price: 17.12, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    { name: "Ruffles Salsa Roja", price: 17.12, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    { name: "Doritos Nacho", price: 17.12, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    { name: "Doritos Pizzerola", price: 17.12, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    { name: "Doritos Incógnita", price: 17.12, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    { name: "Doritos Diablo", price: 17.12, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    { name: "Doritos 3D", price: 17.12, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    { name: "Doritos Flamint Hot", price: 17.12, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    { name: "Doritos Dinamita Chile Limón", price: 17.12, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    { name: "Doritos Dinamita Flamint Hot", price: 17.12, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    { name: "Tostitos Salsa Verde", price: 17.12, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    { name: "Tostitos Flamint Hot", price: 17.12, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    { name: "Rancheritos", price: 15.41, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    { name: "Crujitos", price: 15.41, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    { name: "Fritos Sal Limón", price: 15.41, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    { name: "Fritos Chile Limón", price: 15.41, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    { name: "Fritos Chorizo Chipotle", price: 15.41, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    { name: "Churrumais Original", price: 14.55, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    { name: "Churrumais Flamint Hot", price: 14.55, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    { name: "Cheetos Torciditos", price: 14.55, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    { name: "Cheetos Jalapeño", price: 14.55, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    { name: "Cheetos Flamint Hot", price: 14.55, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    { name: "Cheetos Bolitas", price: 14.55, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    { name: "Cheetos Poffs", price: 14.55, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    { name: "Cheetos Palomita", price: 14.55, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    { name: "Cheetos Colmillo", price: 14.55, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    { name: "Paketaxo Naranja", price: 18.84, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    { name: "Paketaxo Azúl", price: 18.84, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    { name: "Paketaxo Morado", price: 18.84, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    { name: "Paketaxo Verde", price: 18.84, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    { name: "Bolzaza Sabritas Receta Crujiente", price: 21.35, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    { name: "Bolzaza Sabritas Original", price: 21.35, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    { name: "Bolzaza Ruffles Queso", price: 21.35, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    { name: "Bolzaza Doritos Nacho", price: 21.35, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    { name: "Bolzaza Cheetos Torciditos", price: 21.35, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    { name: "Bolzaza Cheetos Flamint Hot ", price: 21.35, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    { name: "Sabritas Original Grande", price: 47.20, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    { name: "Paketaxo Grande Naranja", price: 47.20, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    { name: "Paketaxo Grande Azúl", price: 47.20, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    { name: "Paketaxo Grande Morado", price: 47.20, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    { name: "Paketaxo Grande Verde", price: 47.20, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    { name: "Valentones", price: 32.00, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    { name: "Karate Kat Mag", price: 17.12, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
];