export const TiaRosa = [
    { name: "Pan Wonder Blanco 567g", price: 44.82, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Tia Rosa" },
    { name: "Pan Wonder Integral 567g", price: 46.48, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Tia Rosa" },
    { name: "Chocotorro 50g", price: 12.45, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Tia Rosa" },
    { name: "Dálmata 55g", price: 12.45, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Tia Rosa" },
    { name: "Twinkiew 3p Vainilla 114g", price: 15.77, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Tia Rosa" },
    { name: "Twinkiew 3p Chocolate 114g", price: 15.77, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Tia Rosa" },
    { name: "Bigotes Cajeta 80g", price: 13.28, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Tia Rosa" },
    { name: "Bigotes Chocolate 80g", price: 13.28, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Tia Rosa" },
    { name: "Bigotes Duo Chocolate 160g", price: 20.74, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Tia Rosa" },
    { name: "Conchas 2p 130g", price: 18.26, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Tia Rosa" },
    { name: "Cuernitos 2p 100g", price: 16.60, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Tia Rosa" },
    { name: "Doraditas Clásicas 127g", price: 14.94, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Tia Rosa" },
    { name: "Doraditas Nuez 127g", price: 14.94, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Tia Rosa" },
    { name: "Doraditas Mini 58g", price: 8.30, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Tia Rosa" },
    { name: "Mantecadas Vainilla 3p 157g", price: 21.58, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Tia Rosa" },
    { name: "Mantecadas Chocolate 3p 143g", price: 21.58, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Tia Rosa" },
    { name: "Mantecadas Naranja 3p 165g", price: 21.58, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Tia Rosa" },
    { name: "Muffin Casero 130g", price: 14.94, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Tia Rosa" },
    { name: "Pachoncitos 2p 140g", price: 18.26, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Tia Rosa" },
    { name: "Panqué Casero 235g", price: 29.05, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Tia Rosa" },
    { name: "Polvoroncitos 6p 90g", price: 15.12, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Tia Rosa" },
    { name: "Polvoroncitos Caseros 20p 300g", price: 33.60, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Tia Rosa" },
    { name: "Tartinas 8p Fresa 133.3g", price: 16.80, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Tia Rosa" },
    { name: "Tartinas 8p Piña 133.3g", price: 16.80, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Tia Rosa" },
    { name: "Tartinas 8p Zarzamora 133.3g", price: 16.80, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Tia Rosa" },

    // { name: "", price: 1.00, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    // { name: "", price: 1.00, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    // { name: "", price: 1.00, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    // { name: "", price: 1.00, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    // { name: "", price: 1.00, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    // { name: "", price: 1.00, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    // { name: "", price: 1.00, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
    // { name: "", price: 1.00, piecesPerPackage: 0, image: "", calcType: "divide", unitLabel: "pieza", category: "Sabritas" },
];